controllers:
  adr:
    _target_: sst_base.sim.DummyObject
    prefix: 'mini:adr'
    name: 'adr'
detectors:
  _default:
    _target_: sst_base.detectors.scalar.ADCBuffer
  i0:
    prefix: "mini:i0:"
    name: "ucal_i0up"
  i1:
    prefix: "mini:i1:"
    name: "ucal_i1"
  ref:
    prefix: "mini:ref:"
    name: "ucal_ref"
  sc:
    prefix: "mini:sc:"
    name: "ucal_sc"
  i0mir:
    _target_: sst_base.detectors.scalar.I400SingleCh
    prefix: "XF:07ID-BI{DM7:I400-1}:IC3_MON"
    name: "DM7_i400_i0mirror"
  tes:
    _target_: sst_base.sim.DummyObject
    prefix: "tes"
    name: "tes"
    address: "10.66.48.41"
    path: "/nsls2/data/sst/legacy/ucal/raw/%Y/%m/%2d"
    port: 4000
energy:
  energy:
    _target_: ucal_sim.energy.NewEnPos
    prefix: "mini:energy:"
    name: "en"
gatevalves:
  _default:
    # _target_: sst_base.shutters.EPS_Shutter
    _target_: sst_base.sim.DummyObject
    kind: hinted
    shutter_type: GV
    openval: 0
    closeval: 1
  gv26:
    prefix: "XF:07IDB-VA:2{Mir:M3C-GV:1}"
    name: "Post Shutter Gate Valve"
    openval: 1
    closeval: 0
  gv27:
    prefix: "XF:07IDB-VA:3{Slt:C-GV:1}"
    name: "Upstream Gate Valve"
    openval: 1
    closeval: 0
  gv28:
    prefix: "XF:07IDB-VA:2{BT:1-GV:1}"
    name: "Downstream Gate Valve"
    openval: 1
    closeval: 0
mirrors:
  _default:
    #_target_: sst_base.mirrors.FMBHexapodMirror
    _target_: sst_base.sim.DummyObject
    kind: hinted
  mir4:
    prefix: "XF:07ID2-OP{Mir:M4CD"
    name: "SST 1 Mirror 4 fmb"
  mir3:
    prefix: "XF:07ID1-OP{Mir:M3ABC"
    name: "SST 1 Mirror 3 fmb"
  mir1:
    prefix: "XF:07IDA-OP{Mir:M1"
    name: "SST 1 Mirror 1 fmb"
motors:
  _default:
    _target_: sst_base.motors.PrettyMotor
    kind: hinted
  Exit_Slit:
    prefix: "mini:eslit:"
    name: "Exit Slit of Mono Vertical Gap"
  i0upAu:
    prefix: "mini:i0upAu:"
    name: "i0upAu"
  tesz:
    prefix: "mini:tesz:"
    name: "tesz"
manipulators:
  manipulator:
    _target_: ucal.hw.ManipulatorBuilder
    prefix: "mini:manipulator:"
    name: "manip"
  multimesh:
    _target_: ucal.hw.MultiMeshBuilder
    prefix: "mini:multimesh:"
    name: "i0upmultimesh"
shutters:
  _default:
    _target_: sst_base.shutters.EPS_Shutter
    shutter_type: PH
    openval: 0
    closeval: 1
  psh1:
    prefix: "mini:psh1:"
    name: "Front-End Shutter"
    shutter_type: FE
  psh4:
    prefix: "mini:psh4:"
    name: "Hutch Photon Shutter"
  psh10:
    prefix: "mini:psh10:"
    name: "Upstream Photon Shutter"
  psh7:
    prefix: "mini:psh7:"
    name: "Downstream Photon Shutter"
signals:
  _default:
    _target_: ophyd.EpicsSignalRO
    kind: "normal"
  ring_current:
    prefix: "mini:current"
    name: "NSLS-II Ring Current"
